baseURL = "https://phantomstack.com/"
languageCode = "en-us"
title = "PhantomStack"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true
theme = ["hugo-whisper-theme", "codex"]

[author]
  name = "Akshat Tandon"
  homepage = "https://www.phantomstack.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags"

[params]
  linkedin      = "https://www.linkedin.com/company/phantomstack"
  crunchbase    = "https://www.crunchbase.com/organization/phantomstack"
  github        = "https://github.com/phantomstack"
  email         = "mailto:team@phantomstack.com"
  iconTitles    = ["LinkeIn", "Crunchbase", "GitHub", "Email"]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = '/images/terminal.gif'

[params.homepage_meta_tags]
  meta_description = "Hugo Whisper is a documentation theme built with Hugo."
  meta_og_title = "Hugo Whisper Theme"
  meta_og_type = "website"
  meta_og_url = "https://hugo-whisper.netlify.app"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
  meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

[params.logo]
    mobile = "/images/logo-mobile.svg"
    standard  = "/images/logo.svg"

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "home"
  name = "home"
  title = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "aboutus"
  name = "about us"
  title = "About Us"
  url = "/aboutus"
  weight = 20

[[menu.main]]
  identifier = "platform"
  name = "platform"
  title = "platform"
  url = "/platform"
  weight = 30
    
[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
  weight = 40

[[menu.main]]
  identifier = "impressum"
  name = "impressum"
  title = "Impressum"
  url = "/impressum"
  weight = 40

[[menu.main]]
  identifier = "privacy"
  name = "privacy"
  title = "Privacy Policy"
  url = "/privacy"
  weight = 40
